server:
  port: 8090
  compression:
     enabled: true
     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript
     
spring:
  datasource:
    url: jdbc:jtds:sqlserver://vNTDACLSCRAPR01:1433/WSCRAPER
    username: wscraper_dbo
    password: wscraper_dbo123
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
      default_schema: dbo
      
  resources:
    cache:
      period: 31556926
    static-locations: file:./client/
    
logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    org.apache: WARN
    ch: WARN
